// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func initializeEvent(msg string) (event, error) {
	mainMessage := newMessage(msg)
	mainGreeter := newGreeter(mainMessage)
	mainEvent := newEvent(mainGreeter)
	return mainEvent, nil
}
